global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend_uptime'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://react-project-bucket-1.s3.us-east-1.amazonaws.com/index.html'] 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox_exporter:9115
